/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameType = IDL.Variant({
  'BGMI' : IDL.Null,
  'FreeFire' : IDL.Null,
});
export const UpiId = IDL.Text;
export const Phone = IDL.Text;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'winningsBalance' : IDL.Nat,
  'upiId' : UpiId,
  'phone' : Phone,
  'walletBalance' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'playerId' : IDL.Principal,
  'paymentScreenshotId' : IDL.Text,
  'gamePlayerId' : IDL.Text,
  'playerName' : IDL.Text,
  'phone' : Phone,
  'registeredAt' : IDL.Int,
  'tournamentId' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'Withdrawal' : IDL.Null,
  'CashAdded' : IDL.Null,
  'PrizeWon' : IDL.Null,
  'MatchJoined' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'screenshotId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : TournamentStatus,
  'upiQrImageId' : IDL.Text,
  'thirdPrize' : IDL.Nat,
  'maxSlots' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'secondPrize' : IDL.Nat,
  'description' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'gameType' : GameType,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'prizePool' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveAddCash' : IDL.Func([IDL.Text], [], []),
  'adminApproveWithdrawal' : IDL.Func([IDL.Text], [], []),
  'adminCreditPrize' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'adminRejectAddCash' : IDL.Func([IDL.Text], [], []),
  'adminRejectWithdrawal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTournament' : IDL.Func([IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        GameType,
      ],
      [IDL.Text],
      [],
    ),
  'creditWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'deleteTournament' : IDL.Func([IDL.Text], [], []),
  'getAllUsersWithPrincipal' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPendingTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
  'getTournamentRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournamentWithWallet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'listTournamentsByGameType' : IDL.Func(
      [GameType],
      [IDL.Vec(Tournament)],
      ['query'],
    ),
  'registerForTournament' : IDL.Func(
      [IDL.Text, IDL.Text, Phone, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'requestAddCash' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'requestWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, Phone, UpiId], [], []),
  'setRoomDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePaymentScreenshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, PaymentStatus))],
      [],
      [],
    ),
  'updateTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        TournamentStatus,
        IDL.Text,
        GameType,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameType = IDL.Variant({ 'BGMI' : IDL.Null, 'FreeFire' : IDL.Null });
  const UpiId = IDL.Text;
  const Phone = IDL.Text;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'winningsBalance' : IDL.Nat,
    'upiId' : UpiId,
    'phone' : Phone,
    'walletBalance' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'playerId' : IDL.Principal,
    'paymentScreenshotId' : IDL.Text,
    'gamePlayerId' : IDL.Text,
    'playerName' : IDL.Text,
    'phone' : Phone,
    'registeredAt' : IDL.Int,
    'tournamentId' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'Withdrawal' : IDL.Null,
    'CashAdded' : IDL.Null,
    'PrizeWon' : IDL.Null,
    'MatchJoined' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'screenshotId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : TournamentStatus,
    'upiQrImageId' : IDL.Text,
    'thirdPrize' : IDL.Nat,
    'maxSlots' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'secondPrize' : IDL.Nat,
    'description' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'gameType' : GameType,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'prizePool' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveAddCash' : IDL.Func([IDL.Text], [], []),
    'adminApproveWithdrawal' : IDL.Func([IDL.Text], [], []),
    'adminCreditPrize' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'adminRejectAddCash' : IDL.Func([IDL.Text], [], []),
    'adminRejectWithdrawal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTournament' : IDL.Func([IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          GameType,
        ],
        [IDL.Text],
        [],
      ),
    'creditWalletBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'deleteTournament' : IDL.Func([IDL.Text], [], []),
    'getAllUsersWithPrincipal' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPendingTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
    'getTournamentRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournamentWithWallet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'listTournamentsByGameType' : IDL.Func(
        [GameType],
        [IDL.Vec(Tournament)],
        ['query'],
      ),
    'registerForTournament' : IDL.Func(
        [IDL.Text, IDL.Text, Phone, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'requestAddCash' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'requestWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, Phone, UpiId], [], []),
    'setRoomDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePaymentScreenshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, PaymentStatus))],
        [],
        [],
      ),
    'updateTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          TournamentStatus,
          IDL.Text,
          GameType,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };