/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameType = { 'BGMI' : null } |
  { 'FreeFire' : null };
export type PaymentStatus = { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export type Phone = string;
export interface Registration {
  'id' : string,
  'paymentStatus' : PaymentStatus,
  'playerId' : Principal,
  'paymentScreenshotId' : string,
  'gamePlayerId' : string,
  'playerName' : string,
  'phone' : Phone,
  'registeredAt' : bigint,
  'tournamentId' : string,
}
export interface Tournament {
  'id' : string,
  'startTime' : bigint,
  'status' : TournamentStatus,
  'upiQrImageId' : string,
  'thirdPrize' : bigint,
  'maxSlots' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'secondPrize' : bigint,
  'description' : string,
  'roomPassword' : [] | [string],
  'gameType' : GameType,
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'prizePool' : bigint,
}
export type TournamentStatus = { 'Live' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'txType' : TransactionType,
  'screenshotId' : string,
  'amount' : bigint,
}
export type TransactionStatus = { 'Rejected' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type TransactionType = { 'Withdrawal' : null } |
  { 'CashAdded' : null } |
  { 'PrizeWon' : null } |
  { 'MatchJoined' : null };
export type UpiId = string;
export interface UserProfile {
  'name' : string,
  'winningsBalance' : bigint,
  'upiId' : UpiId,
  'phone' : Phone,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveAddCash' : ActorMethod<[string], undefined>,
  'adminApproveWithdrawal' : ActorMethod<[string], undefined>,
  'adminCreditPrize' : ActorMethod<[Principal, bigint, string], undefined>,
  'adminRejectAddCash' : ActorMethod<[string], undefined>,
  'adminRejectWithdrawal' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTournament' : ActorMethod<[string], undefined>,
  'createTournament' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      GameType,
    ],
    string
  >,
  'creditWalletBalance' : ActorMethod<[Principal, bigint], undefined>,
  'deleteTournament' : ActorMethod<[string], undefined>,
  'getAllUsersWithPrincipal' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPendingTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTournament' : ActorMethod<[string], Tournament>,
  'getTournamentRegistrations' : ActorMethod<[string], Array<Registration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournamentWithWallet' : ActorMethod<[string, string], string>,
  'listTournamentsByGameType' : ActorMethod<[GameType], Array<Tournament>>,
  'registerForTournament' : ActorMethod<
    [string, string, Phone, string, string],
    string
  >,
  'requestAddCash' : ActorMethod<[bigint, string], string>,
  'requestWithdrawal' : ActorMethod<[string, bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[string, Phone, UpiId], undefined>,
  'setRoomDetails' : ActorMethod<[string, string, string], undefined>,
  'updatePaymentScreenshot' : ActorMethod<[string, string], undefined>,
  'updatePaymentStatus' : ActorMethod<
    [Array<[string, PaymentStatus]>],
    undefined
  >,
  'updateTournament' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      TournamentStatus,
      string,
      GameType,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];