/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentStatus = { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface PaymentStatusUpdate {
  'newStatus' : PaymentStatus,
  'registrationId' : string,
}
export interface Registration {
  'id' : string,
  'paymentStatus' : PaymentStatus,
  'playerId' : Principal,
  'email' : string,
  'paymentScreenshotId' : string,
  'playerName' : string,
  'phone' : string,
  'bgmiId' : string,
  'registeredAt' : bigint,
  'tournamentId' : string,
}
export interface Tournament {
  'id' : string,
  'startTime' : bigint,
  'status' : TournamentStatus,
  'upiQrImageId' : string,
  'maxSlots' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'roomPassword' : [] | [string],
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'prizePool' : string,
}
export type TournamentStatus = { 'Live' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, string],
    string
  >,
  'deleteTournament' : ActorMethod<[string], undefined>,
  'getCallerRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTournament' : ActorMethod<[string], Tournament>,
  'getTournamentRegistrations' : ActorMethod<[string], Array<Registration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'registerForTournament' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRoomDetails' : ActorMethod<[string, string, string], undefined>,
  'updatePaymentScreenshot' : ActorMethod<[string, string], undefined>,
  'updatePaymentStatus' : ActorMethod<[Array<PaymentStatusUpdate>], undefined>,
  'updateTournament' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      TournamentStatus,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];