/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Phone = IDL.Text;
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'playerId' : IDL.Principal,
  'paymentScreenshotId' : IDL.Text,
  'playerName' : IDL.Text,
  'phone' : Phone,
  'bgmiId' : IDL.Text,
  'registeredAt' : IDL.Int,
  'tournamentId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : Phone });
export const TournamentStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : TournamentStatus,
  'upiQrImageId' : IDL.Text,
  'maxSlots' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'prizePool' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTournament' : IDL.Func([IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteTournament' : IDL.Func([IDL.Text], [], []),
  'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
  'getTournamentRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'registerForTournament' : IDL.Func(
      [IDL.Text, IDL.Text, Phone, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRoomDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePaymentScreenshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, PaymentStatus))],
      [],
      [],
    ),
  'updateTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        TournamentStatus,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Phone = IDL.Text;
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'playerId' : IDL.Principal,
    'paymentScreenshotId' : IDL.Text,
    'playerName' : IDL.Text,
    'phone' : Phone,
    'bgmiId' : IDL.Text,
    'registeredAt' : IDL.Int,
    'tournamentId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : Phone });
  const TournamentStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : TournamentStatus,
    'upiQrImageId' : IDL.Text,
    'maxSlots' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'prizePool' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTournament' : IDL.Func([IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Text], [], []),
    'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTournament' : IDL.Func([IDL.Text], [Tournament], ['query']),
    'getTournamentRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'registerForTournament' : IDL.Func(
        [IDL.Text, IDL.Text, Phone, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRoomDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePaymentScreenshot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, PaymentStatus))],
        [],
        [],
      ),
    'updateTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          TournamentStatus,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };